<?php

namespace AppBundle\Repository;

/**
 * BlockDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockDataRepository extends \Doctrine\ORM\EntityRepository
{
}
