<?php

namespace AppBundle\Repository;

/**
 * CvDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvDataRepository extends \Doctrine\ORM\EntityRepository
{
}