<?php

namespace AppBundle\Repository;

/**
 * CVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVRepository extends \Doctrine\ORM\EntityRepository
{
}
