<?php
/**
 * Created by PhpStorm.
 * User: svidleo
 * Date: 24/08/2017
 * Time: 00:03
 */

namespace AppBundle\Repository;


/**
 * EventSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSourceRepository extends \Doctrine\ORM\EntityRepository
{

}