<?php

namespace AppBundle\Repository;

/**
 * TemplateSlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateSlotRepository extends \Doctrine\ORM\EntityRepository
{
}
