<?php

namespace AppBundle\Repository;

/**
 * WorkExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}