# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  AppBundle\Service\:
    resource: '../../src/AppBundle/Service/*'
    public: true
  app.redirect_after_registration_subscriber:
    class: AppBundle\EventListener\RedirectAfterRegistrationSubscriber
    arguments:
      - "@router"
    tags:
        - { name: kernel.event_subscriber }
